name: Auto Cascade Merge

on:
  push:
    branches:
      - 'main'

jobs:
  auto-cascade-develop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Raise Pull Request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "develop"
        pr_title: "Cascade Merge to Develop"
        pr_body: "ðŸ‘‘ *Automated Pull Request to Develop*"
        pr_draft: false
        pr_label: "AutoCICD"
        github_token: "${{ secrets.HUB_TOKEN }}"
